### ISSUE TITLE
有放完整代码和model的计划？

### ISSUE THREAD

**Issue by shipengai** [LaVi-Lab/Visual-Table#1]

**Comment by HenryHZY** [comment]
Yes, we plan to release the code and checkpoints later.

**Comment by MonolithFoundation** [comment]
I think the data is more important to release..... 

From I can tell, there is no code changes compare to original LLaVA, are they?

**Comment by YiwuZhong** [comment]
@shipengai @MonolithFoundation Thank you for your interest in our work. Now we release both code and annotations. More details can be found in the README.
